name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - dev2
          - testing
          - staging
      incrementVersion:
        description: 'Bump Version?'
        type: boolean
        required: false
      versionType:
        description: 'Version to bump (major.minor.patch)'
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  deploy:
    env:
      PACKAGE_LOCATION: packages/telemed-intake/app
      ZAMBDAS_LOCATION: packages/telemed-intake/zambdas
      SLACK_NOTIFICATION_SERVICE_NAME: ottehr-notifications

    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    strategy:
      matrix:
        node-version: [18.18.0]

    steps:
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.OTTEHR_DEMO_PRIVATE_KEY }}
            ${{ secrets.BUMP_VERSION }}

      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.BUMP_VERSION }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Check out secrets repo to grab the env file.
        uses: actions/checkout@v3
        with:
          repository: masslight/ottehr-secrets
          ssh-key: ${{ secrets.OTTEHR_DEMO_PRIVATE_KEY }}
          path: 'secrets'

      - name: Move secrets file into the .env directory.
        run: mkdir -p ${{ env.ZAMBDAS_LOCATION }}/.env/ && cp secrets/telemed-intake/* ${{ env.ZAMBDAS_LOCATION }}/.env/

      - name: Copy env file to local.env to support serverless package command
        run: cp ${{ env.ZAMBDAS_LOCATION }}/.env/${{ github.event.inputs.environment }}.json ${{ env.ZAMBDAS_LOCATION }}/.env/local.json

      - name: Increase version if input dictates.
        if: ${{ github.event.inputs.incrementVersion == 'true' }}
        run: |
          git config --local user.email "ngreene+ottehrghaction@masslight.com"
          git config --local user.name "GitHub Action Bump Version"
          pnpm version ${{ github.event.inputs.versionType }}

      - name: Push increased version if input dictates.
        if: ${{ github.event.inputs.incrementVersion == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: ${{ github.ref }}

      - name: Get Version Number from package.json for build notifications.
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: ${{ env.PACKAGE_LOCATION }}

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build:telemed-intake

      - name: Setup zapehr secrets
        run: cd ${{ env.ZAMBDAS_LOCATION }} && pnpm setup-zapehr-secrets:${{ github.event.inputs.environment }}

      - name: Deploy zambdas
        run: cd ${{ env.ZAMBDAS_LOCATION }} && pnpm deploy-zambdas:${{ github.event.inputs.environment }}

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS S3
        run: |
          aws s3 sync ./packages/telemed-intake/app/build s3://telemed.ottehr.com --delete

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name ottehr-telemed-intake-dev --zip-file fileb://function.zip

>>>>>>> 722ec45 (fix build errors and create deploy file)
=======
>>>>>>> 358b140 (remove vercel from deploy yml)
      - name: Notify Slack
        if: always()
        uses: edge/simple-slack-notify@v1.1.2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          BRANCH: ${{ github.ref }}
          PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version }}
        with:
          channel: '#ottehr-notifications'
          status: ${{ job.status }}
          success_text: '${{ env.GITHUB_WORKFLOW }} (Run #${{ env.GITHUB_RUN_NUMBER }}) deploy completed successfully'
          failure_text: '${{ env.GITHUB_WORKFLOW }} (Run #${{ env.GITHUB_RUN_NUMBER }}) deploy failed'
          cancelled_text: '${{ env.GITHUB_WORKFLOW }} (Run #${{ env.GITHUB_RUN_NUMBER }}) deploy was cancelled'
          fields: |
            [{ "title": "Service", "value": "${{ env.SLACK_NOTIFICATION_SERVICE_NAME }}", "short": true },
            { "title": "Action URL", "value": "${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}"},
            { "title": "Branch", "value": "${{ env.BRANCH }}", "short": true },
            { "title": "Environment", "value": "${{ env.ENVIRONMENT }}", "short": true },
            { "title": "Version", "value": "${{ env.PACKAGE_VERSION }}", "short": true }]
=======
      # - name: Notify Slack
      #   if: always()
      #   uses: edge/simple-slack-notify@v1.1.2
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     BRANCH: ${{ github.ref }}
      #     PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version }}
      #   with:
      #     channel: '#ottehr-notifications'
      #     status: ${{ job.status }}
      #     success_text: '${{ env.GITHUB_WORKFLOW }} (Run #${{ env.GITHUB_RUN_NUMBER }}) deploy completed successfully'
      #     failure_text: '${{ env.GITHUB_WORKFLOW }} (Run #${{ env.GITHUB_RUN_NUMBER }}) deploy failed'
      #     cancelled_text: '${{ env.GITHUB_WORKFLOW }} (Run #${{ env.GITHUB_RUN_NUMBER }}) deploy was cancelled'
      #     fields: |
      #       [{ "title": "Service", "value": "${{ env.SLACK_NOTIFICATION_SERVICE_NAME }}", "short": true },
      #       { "title": "Action URL", "value": "${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}"},
      #       { "title": "Branch", "value": "${{ env.BRANCH }}", "short": true },
      #       { "title": "Environment", "value": "${{ env.ENVIRONMENT }}", "short": true },
      #       { "title": "Version", "value": "${{ env.PACKAGE_VERSION }}", "short": true }]
>>>>>>> bf2b1b4 (checkout the env variables from secrets repo)
